# This is a basic workflow to help you get started with Actions

name: Build Release

# Controls when the workflow will run
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      # Runs a set of commands using the runners shell
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Build
        run: |
          sudo apt -y install upx
          pip install -r requirements.txt
          pip install pyinstaller
          pyinstaller --clean spyglass.py -F -n Spyglass-Executable -c
          
      - name: Push Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            dist/Spyglass-Executable
